name: Build and Deploy Jekyll to Github Pages by running examples using quarto

on:
  push:
    branches: [ main ]

jobs:
  build-quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Remove files from cache
        run: rm -rf ./quarto_files/_build/ ./quarto_files/_freeze/ ./quarto_files/.quarto/

      - name: Render quarto pages
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ./quarto_files/
          to: html

  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Build Jekyll 🏗
        uses:  helaili/jekyll-action@v2
        with:
          #token: ${{ secrets.GH_PAGES_TOKEN }}
          #target_branch: 'gh-pages'
          jekyll_src: './'
          jekyll_build_options: '--destination ./_site'
          build_only: true

      - name: Install node dependencies
        run: npm install

      - name: Optimize AMP ⚡ and Minify HTML 🗜
        run: |
          sudo chmod -R 777 ./_site
          npx gulp build

      - name: Deploy to gh-page 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: '_site'
